name: CI
on: push


jobs:
  black:
    name: Black formatted
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v1
       with:
         python-version: 3.7
     - name: Check all Python files
       run: |
         pip install black
         git ls-files | grep '\.py$' | xargs black
         git diff --color=always --exit-code

  install:
    name: Install as rez package (${{ matrix.yum_python }})
    runs-on: ubuntu-latest
    container:
      image: "centos:7"
    strategy:
      matrix:
        yum_python:
          - "python"  # Python 2.7
          - "python3" # Python 3.6

    steps:
      - run: yum install -y ${{ matrix.yum_python }}
      - uses: j0yu/setup-rez@v1
        with:
          pythonExe: ${{ matrix.yum_python }}

      - name: Setup yum assumeyes, sudo and docker
        run: |
          echo "assumeyes=1" >> /etc/yum.conf
          yum install sudo
          curl -L https://get.docker.com/ | bash -s

      # git
      - uses: actions/checkout@v2
        with:
          repository: j0yu/rez-git
          path: git
      - run: rez build --install
        working-directory: ./git

      # ostree
      - uses: actions/checkout@v2
        with:
          path: ostree
      - run: rez build --install
        working-directory: ./ostree

      - run: rez env libostree -c 'ls -l $REZ_LIBOSTREE_ROOT/lib/libsotree*.so*'
